# Copyright 2026, Diogo Costa, diogo.costa@uevora.pt
# This file is part of OpenWQ model.

# This program, openWQ, is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os
sys.path.insert(0, 'config_support_lib')

import Gen_Input_Driver as gJSON_lib
from Gen_Input_Driver import uniform_param

# ╔════════════════════════════════════════════════════════════════════════╗
# ║                 OpenWQ MODEL CONFIGURATION TEMPLATE                    ║
# ╠════════════════════════════════════════════════════════════════════════╣
# ║                                                                        ║
# ║  HOW TO USE:                                                           ║
# ║    1. Copy this file (keep it here — needs config_support_lib/)        ║
# ║    2. Update the paths in Section 1 (executable & control file)        ║
# ║    3. Choose which modules to enable/disable in Section 4              ║
# ║    4. Configure source/sink loads in Section 5                         ║
# ║    5. Set the output species in Section 7                              ║
# ║    6. Run:  python model_config_template.py                            ║
# ║                                                                        ║
# ║  SECTIONS:                                                             ║
# ║    1. General Information      — project metadata & file paths         ║
# ║    2. Computational Settings   — solver, threads, debug mode           ║
# ║    3. Initial Conditions       — starting concentrations               ║
# ║    4. Physics Modules:                                                 ║
# ║       a. Biogeochemistry (BGC) — reaction kinetics or geochemistry     ║
# ║       b. Transport Dissolved   — advection & dispersion                ║
# ║       c. Lateral Exchange      — vertical mixing between compartments  ║
# ║       d. Sediment Transport    — erosion & suspended sediment          ║
# ║       e. Sorption Isotherm     — dissolved ↔ sorbed phase exchange     ║
# ║    5. Source/Sink Loads        — nutrient inputs (CSV, LULC, or ML)    ║
# ║    6. External Water Fluxes    — boundary conditions from other models ║
# ║    7. Output Settings          — species, format, timestep             ║
# ║    8. Docker Settings          — MPI processes for model execution      ║
# ║    9. Report Generation        — HTML report with maps & time series   ║
# ║                                                                        ║
# ║  Full documentation: https://openwq.readthedocs.io                     ║
# ╚════════════════════════════════════════════════════════════════════════╝


# ──────────────────────────────────────────────────────────────────────────────
#  SECTION 1: GENERAL INFORMATION
# ──────────────────────────────────────────────────────────────────────────────
#  Project metadata (used in the HTML report header) and paths to the
#  compiled executable and the host-model control file.
#
#  ⚠  UPDATE THESE PATHS before running — they must point to YOUR local files.
#     When using Docker/Apptainer, provide host paths; they are automatically
#     converted to container paths at runtime.

project_name = "Simulation Report"
geographical_location = "NA"
authors = "Diogo Costa"
date = "January, 2026"
comment = "Report auto-generated by model_config_template.py — edit project_name and comment to customize"

# Host model that OpenWQ is coupled to.
# Options: "mizuroute" (river routing) | "summa" (land surface)
hostmodel = "mizuroute"

# Full path to the compiled executable (on the HOST machine).
# All OpenWQ config files (openwq_in/, openWQ_master.json) and outputs
# (openwq_out/) are generated in the same directory as the executable.
executable_path = (
    "/Users/diogocosta/Documents/openwq_code/diogo_test/mizuRoute-OpenWQ/"
    "route/build/openwq/openwq/bin/mizuroute_openwq_Release"
)

# Full path to the mizuRoute/SUMMA control file (on the HOST machine).
file_manager_path = (
    "/Users/diogocosta/Documents/openwq_code/diogo_test/mizuRoute-OpenWQ/"
    "route/build/openwq/openwq/bin/mizuroute_in/"
    "BakerCreek_2x2_example/settings/testCase_cameo_case3.control_E5evap"
)


# ──────────────────────────────────────────────────────────────────────────────
#  SECTION 2: COMPUTATIONAL SETTINGS
# ──────────────────────────────────────────────────────────────────────────────

# Numerical solver for the reaction system.
# "FORWARD_EULER" — fast, first-order explicit (good for simple kinetics)
# "SUNDIALS"      — implicit adaptive solver (better for stiff systems)
solver = "FORWARD_EULER"

# Print solver derivatives to the log
# Useful to investigate the causes of concentration dynamics, but it will generate more model outputs.
run_mode_debug = True

# Number of OpenMP threads. Set to "all" to use every available core.
use_num_threads = 4


# ──────────────────────────────────────────────────────────────────────────────
#  SECTION 3: INITIAL CONDITIONS
# ──────────────────────────────────────────────────────────────────────────────
#  Sets a uniform starting concentration for ALL species in ALL compartments.
#  For spatially-varying ICs, use source/sink files to ramp up from zero.

ic_all_value = 2          # Starting concentration value
ic_all_units = "mg/l"     # Units: "mg/l", "kg", "g", etc.


# ──────────────────────────────────────────────────────────────────────────────
#  SECTION 4a: BIOGEOCHEMISTRY MODULE (BGC)
# ──────────────────────────────────────────────────────────────────────────────
#  Controls how chemical reactions are computed.
#
#  "NATIVE_BGC_FLEX" — User-defined kinetic expressions (recommended for most
#                      nutrient cycling applications: nitrification, denitrification,
#                      mineralization, etc.)
#                      Pre-built templates available in:
#                        config_support_lib/BGC_templates/NATIVE_BGC_FLEX/popular_models/
#
#  "PHREEQC"         — Full geochemical equilibrium engine (for mineral dissolution,
#                      ion exchange, surface complexation, etc.)
#                      Docs: https://openwq.readthedocs.io → Modules → PHREEQC

bgc_module_name = "NATIVE_BGC_FLEX"

# ── NATIVE_BGC_FLEX settings ──
# ⚠ Only used if bgc_module_name = "NATIVE_BGC_FLEX"; ignored otherwise.
# Path to the JSON file describing reactions, species, and rate constants.
# Browse available templates:
#   config_support_lib/BGC_templates/NATIVE_BGC_FLEX/popular_models/
#     SWAT_full_nutrients.json    — full N & P cycling (SWAT-based)
#     simple_nitrification.json   — NH4 → NO3 only
#     ... (see folder for more)
path2selected_NATIVE_BGC_FLEX_framework = "config_support_lib/BGC_templates/NATIVE_BGC_FLEX/popular_models/SWAT_full_nutrients.json"

# NOTE on species naming:
#   Templates use the "as element" convention for nutrients:
#     NO3-N (nitrate as nitrogen, mg-N/L),  NH4-N, NO2-N
#     PO4-P (phosphate as phosphorus, mg-P/L),  SO4-S
#   GRQA observations report the full ion (e.g. NO3 in mg-NO3/L).
#   The stoichiometric conversion is applied automatically:
#     model_value = GRQA_value × MW(element) / MW(ion)
#   See BGC_templates/README.md for the full conversion table.

# ── PHREEQC settings ──
# ⚠ Only used if bgc_module_name = "PHREEQC"; ignored otherwise.
phreeqc_input_filepath = "config_support_lib/examples_PHREEQC/phreeqc_river.pqi"
phreeqc_database_filepath = "config_support_lib/examples_PHREEQC/phreeqc.dat"
phreeqc_mobile_species = ["H", "O", "Charge", "Ca"]   # Must match PHREEQC components
phreeqc_component_h2o = True

# Temperature mapping: tells OpenWQ which host-model variable provides
# water temperature for each compartment.
# NOTE: OpenWQ auto-converts Kelvin → Celsius (detects K if value > 100).
#   mizuRoute: use "Treach_K"  (from basinAirTemp)
#   SUMMA:     use "Tair_K" or "Tsoil_K"
phreeqc_temperature_mapping = {"RIVER_NETWORK_REACHES": "Treach_K"}  # or None
phreeqc_pressure_mapping = None   # Maps compartment → pressure variable (atm). Usually None.

# Species name override. Leave [] to auto-detect from the .pqi file.
# TIP: Run once with [] and check the log to see detected component names.
phreeqc_chemical_species_names = []


# ──────────────────────────────────────────────────────────────────────────────
#  SECTION 4b: DISSOLVED TRANSPORT MODULE
# ──────────────────────────────────────────────────────────────────────────────
#  Controls how dissolved species move with the water.
#
#  "NATIVE_TD_ADV"              — Pure advection (transport by water flow only)
#  "OPENWQ_NATIVE_TD_ADVDISP"  — Advection + dispersion (adds mixing/diffusion)
#  "NONE"                       — Disable dissolved transport

td_module_name = "OPENWQ_NATIVE_TD_ADVDISP"

# ── Dispersion settings ──
# ⚠ Only used if td_module_name = "OPENWQ_NATIVE_TD_ADVDISP"; ignored otherwise.
# Dispersion coefficients [Dx, Dy, Dz] in m²/s.
# Typical river values: 0.1–10 m²/s. Higher = more mixing.
td_module_dispersion_xyz = [0.3, 0.3, 0.3]

# Characteristic length between cell centers [m].
# Used to scale the dispersion gradient (Fick's law: J = -D * dC/dx).
td_module_characteristic_length_m = 100.0


# ──────────────────────────────────────────────────────────────────────────────
#  SECTION 4c: LATERAL EXCHANGE MODULE
# ──────────────────────────────────────────────────────────────────────────────
#  Vertical mixing between stacked compartments (e.g., runoff ↔ soil water).
#
#  "NATIVE_LE_BOUNDMIX"  — Exchange proportional to concentration gradient × K
#  "NONE"                 — No lateral/vertical exchange

le_module_name = "NATIVE_LE_BOUNDMIX"

# ── NATIVE_LE_BOUNDMIX settings ──
# ⚠ Only used if le_module_name = "NATIVE_LE_BOUNDMIX"; ignored otherwise.
# Exchange configuration: one entry per interface between compartments.
#   direction           — exchange axis: "x", "y", or "z"
#   upper_compartment   — compartment on top (e.g., surface runoff)
#   lower_compartment   — compartment below (e.g., soil water)
#   K_val               — exchange coefficient [1/s]. Larger = faster mixing.
le_module_config = [
    {
        "direction": "z",
        "upper_compartment": "RUNOFF",
        "lower_compartment": "ILAYERVOLFRACWAT_SOIL",
        "K_val": 0.000000001
    }
]


# ──────────────────────────────────────────────────────────────────────────────
#  SECTION 4d: SEDIMENT TRANSPORT MODULE
# ──────────────────────────────────────────────────────────────────────────────
#  Erosion and suspended sediment dynamics.
#  Docs: https://openwq.readthedocs.io → Modules → Transport Sediments
#
#  "HYPE_MMF"    — Morgan–Morgan–Finney model (physically-based erosion)
#  "HYPE_HBVSED" — HBV-SED model (simpler, empirical erosion)
#  "NONE"        — Disable sediment transport

ts_module_name = "HYPE_HBVSED"

# Which compartment experiences erosion and receives transported sediment.
ts_sediment_compartment = "RIVER_NETWORK_REACHES"
ts_transport_compartment = "RIVER_NETWORK_REACHES"
ts_direction = "z"
ts_erosion_inhibit_compartment = "RIVER_NETWORK_REACHES"
ts_data_format = "JSON"

# ── HYPE_MMF parameters ──
# ⚠ Only used if ts_module_name = "HYPE_MMF"; ignored otherwise.
# Physical soil erosion properties applied uniformly.
# Override per-cell using ts_mmf_parameters below.
ts_mmf_defaults = {
    "COHESION": 7.5,           # Soil cohesion [kPa]
    "ERODIBILITY": 2.0,        # Soil erodibility [g/J]
    "SREROEXP": 1.2,            # Splash erosion exponent [-]
    "CROPCOVER": 0.5,           # Fraction of crop cover [0–1]  ⎫ Must sum
    "GROUNDCOVER": 0.5,         # Fraction of ground cover [0–1] ⎭ to 1.0
    "SLOPE": 0.4,               # Terrain slope [m/m]
    "TRANSPORT_FACTOR_1": 0.2,  # Sediment transport capacity factor 1
    "TRANSPORT_FACTOR_2": 0.5   # Sediment transport capacity factor 2
}
# Spatially-varying overrides. Leave as-is for uniform parameters.
# To vary spatially, replace uniform_param() with per-cell dictionaries.
ts_mmf_parameters = {k: uniform_param(v) for k, v in ts_mmf_defaults.items()}

# ── HYPE_HBVSED parameters ──
# ⚠ Only used if ts_module_name = "HYPE_HBVSED"; ignored otherwise.
ts_hbvsed_defaults = {
    "SLOPE": 0.4,                                    # Terrain slope [m/m]
    "EROSION_INDEX": 0.4,                             # Soil erosion susceptibility [-]
    "SOIL_EROSION_FACTOR_LAND_DEPENDENCE": 0.4,       # Land-use erosion factor [-]
    "SOIL_EROSION_FACTOR_SOIL_DEPENDENCE": 0.4,       # Soil-type erosion factor [-]
    "SLOPE_EROSION_FACTOR_EXPONENT": 1.5,             # Nonlinear slope effect [-]
    "PRECIP_EROSION_FACTOR_EXPONENT": 1.5,            # Nonlinear rainfall effect [-]
    "PARAM_SCALING_EROSION_INDEX": 0.5                # Scaling factor for erosion index [-]
}
# Spatially-varying overrides. Leave as-is for uniform parameters.
ts_hbvsed_parameters = {k: uniform_param(v) for k, v in ts_hbvsed_defaults.items()}

# Monthly erosion factor (12 values, Jan→Dec).
# Applied as: erosion_month = 1.0 + factor[month]
# Use to represent seasonal vegetation / freeze-thaw effects.
ts_hbvsed_monthly_erosion_factor = [0.0] * 12


# ──────────────────────────────────────────────────────────────────────────────
#  SECTION 4e: SORPTION ISOTHERM MODULE
# ──────────────────────────────────────────────────────────────────────────────
#  Controls dissolved ↔ sorbed phase partitioning.
#
#  "FREUNDLICH" — Nonlinear sorption: q = Kfr * C^Nfr
#  "LANGMUIR"   — Saturation sorption: q = qmax * KL * C / (1 + KL * C)
#  "NONE"       — No sorption
#
#  ⚠  Only compatible with NATIVE_BGC_FLEX.
#     When using PHREEQC, set "NONE" — PHREEQC handles sorption internally
#     via SURFACE/EXCHANGE blocks in the .pqi file.

si_module_name = "NONE"
si_sediment_compartment = "RIVER_NETWORK_REACHES"
si_bulk_density_kg_m3 = 1500.0    # Sediment bulk density [kg/m³]
si_layer_thickness_m = 1.0        # Active sediment layer thickness [m]

# Per-species sorption parameters. Set None when si_module_name = "NONE".
#
# FREUNDLICH example:
#   si_species_params = {
#       "NH4-N": {"Kfr": 0.5, "Nfr": 0.8, "Kadsdes_1_per_s": 1e-6}
#   }
#
# LANGMUIR example:
#   si_species_params = {
#       "PO4-P": {"qmax_mg_per_kg": 200.0, "KL_L_per_mg": 0.01,
#                  "Kadsdes_1_per_s": 1e-6}
#   }
si_species_params = None


# ──────────────────────────────────────────────────────────────────────────────
#  SECTION 5: SOURCE/SINK LOADS
# ──────────────────────────────────────────────────────────────────────────────
#  Defines how nutrient/pollutant loads enter or leave the system.
#
#  METHOD OPTIONS:
#  ┌──────────────────────────────────────────┬──────────────────────────────┐
#  │ Method                                   │ When to use                  │
#  ├──────────────────────────────────────────┼──────────────────────────────┤
#  │ "load_from_csv"                          │ You have measured load data  │
#  │ "using_copernicus_lulc_with_static_coeff"│ Estimate from land use maps  │
#  │ "using_copernicus_lulc_with_dynamic_coeff"│ Land use + climate effects  │
#  │ "ml_model"                               │ Train from monitoring data   │
#  │ "none"                                   │ No external loads            │
#  └──────────────────────────────────────────┴──────────────────────────────┘
#
#  ⚠  When using PHREEQC, set "none" unless CSV species match PHREEQC components.

ss_method = "using_copernicus_lulc_with_static_coeff"

# Metadata (recorded in the generated JSON for documentation purposes).
ss_metadata_source = "Just for demonstration"
ss_metadata_comment = "Leave any comments needed for future reference"


# ── METHOD 1: Load from CSV ──────────────────────────────────────────────────
# ⚠ Only used if ss_method = "load_from_csv"; ignored otherwise.
#  Provide one entry per species × compartment combination.
#  Each CSV file has columns: datetime, cell_id_1, cell_id_2, ...
#  Values are load rates in the specified units.

ss_method_csv_config = [
    {
        "Chemical_name": "N_ORG_active",                    # Species name (must match BGC)
        "Compartment_name": "RIVER_NETWORK_REACHES",        # Target compartment
        "Type": "source",                                   # "source" (adds) or "sink" (removes)
        "Units": "kg",                                      # Load units per timestep
        "Filepath": "/Users/diogocosta/Documents/openwq_code/6_mizuroute_cslm_openwq/route/build/openwq/openwq/supporting_scripts/Model_Config/config_support_lib/examples_SS_in_cvs/N_ORG_active_fertilizer.csv",
        "Delimiter": ","
    },
    {
        "Chemical_name": "NH4-N",
        "Compartment_name": "RIVER_NETWORK_REACHES",
        "Type": "source",
        "Units": "kg",
        "Filepath": "/Users/diogocosta/Documents/openwq_code/6_mizuroute_cslm_openwq/route/build/openwq/openwq/supporting_scripts/Model_Config/config_support_lib/examples_SS_in_cvs/NH4_fertilizer.csv",
        "Delimiter": ","
    }
]


# ── METHOD 2 & 3: Copernicus LULC ────────────────────────────────────────────
# ⚠ Only used if ss_method = "using_copernicus_lulc_with_*"; ignored otherwise.
#  Estimates loads from ESA CCI Land Cover maps × export coefficients.
#  Requires: basin shapefile + (optionally) OpenWQ HDF5 output for cell mapping.

# Basin shapefile — defines the spatial extent and sub-catchment boundaries.
ss_method_copernicus_basin_info = {
    'path_to_shp': '/Users/diogocosta/Documents/openwq_code/6_mizuroute_cslm_openwq/test_case/mizuroute_in/shapefiles/finalcat_info_v1-0.shp',
    'mapping_key': 'SubId'    # Column in shapefile that identifies each sub-catchment
}

# HDF5 output file — used to map host-model IDs to OpenWQ grid indices.
# Only needed when ss_use_cellid_mapping = False (legacy mode).
ss_method_copernicus_openwq_h5_results_file_example_for_mapping_key = {
    'path_to_file': '/Users/diogocosta/Documents/openwq_code/6_mizuroute_cslm_openwq/test_case/openwq_out/HDF5/RIVER_NETWORK_REACHES@N_ORG_ACTIVE#MG|L-main.h5',
    'mapping_key': 'reachID'
}

# Which compartment receives the loads.
ss_method_copernicus_compartment_name_for_load = "RIVER_NETWORK_REACHES"

# Path to Copernicus ESA CCI Land Cover data.
#   None → auto-download from CDS (requires: pip install cdsapi + ~/.cdsapirc)
#          Downloads the global file (~2.2 GB), clips to basin bbox, deletes global.
#          API setup: https://cds.climate.copernicus.eu/how-to-api
#   path → use a local directory with pre-downloaded NetCDF/GeoTIFF files.
#          Manual download: https://cds.climate.copernicus.eu/datasets/satellite-land-cover
ss_method_copernicus_nc_lc_dir = '/Users/diogocosta/Documents/ESACCI-LC/'

# Simulation period [start_year, end_year].
#   None → auto-detected from the host-model control file (file_manager_path).
#          Reads <sim_start>/<sim_end> for mizuRoute or simStartTime/simEndTime for SUMMA.
#   [start, end] → override with explicit years (e.g., [1993, 2020]).
#   Copernicus ESA CCI LC is available for 1992–2022.
ss_method_copernicus_period = None

# What to do if the simulation period falls outside the Copernicus range (1992–2022)?
#   True  → use the nearest available year as proxy (e.g., 1985 → uses 1992 data)
#   False → abort with an error explaining the mismatch
ss_method_copernicus_use_proxy_if_outside_range = True

# Use built-in export coefficients (literature-based defaults)?
#   True  → uses internal lookup table of nutrient loads per LULC class.
#   False → you must provide custom coefficients below.
ss_method_copernicus_default_loads_bool = True

# Custom export coefficients (only when default_loads_bool = False).
# Format: { LULC_class_code: { "species": load_kg_per_ha_per_year, ... } }
# LULC class codes: 10=cropland, 50=forest, 130=grassland, etc.
# Full class list: https://maps.elie.ucl.ac.be/CCI/viewer/download/ESACCI-LC-Legend.csv
ss_method_copernicus_optional_custom_annual_load_coeffs_per_lulc_class = {
    10:  {'TN': 20.0, 'TP': 3.0,  'NH4': 2.5},    # Cropland
    50:  {'TN': 2.0,  'TP': 0.1,  'NH4': 0.2},     # Forest
    130: {'TN': 5.0,  'TP': 0.15, 'NH4': 0.5}      # Grassland
}

# How to distribute annual loads across months.
#   "uniform"  — equal 1/12 each month
#   "seasonal" — climate-weighted (requires ss_climate_data below)
ss_method_copernicus_annual_to_seasonal_loads_method = 'uniform'


# ── Cell ID Mapping ──────────────────────────────────────────────────────────
#  Controls how spatial locations are identified in the generated JSON files.
#
#   True  (recommended) — Uses host-model cell IDs directly (e.g., reachID
#         for mizuRoute, hruId_z{layer} for SUMMA). Portable across grids.
#   False (legacy)      — Uses internal (ix, iy, iz) indices. Requires the
#         HDF5 mapping file above.
#
#  TIP: To find valid cell IDs, check your HDF5 outputs:
#    import h5py
#    with h5py.File('openwq_out/HDF5/RIVER_NETWORK_REACHES@NO3-N#MG|L-main.h5') as f:
#        print(f['reachID'][:])    # mizuRoute
#        print(f['hruId'][:])      # SUMMA
ss_use_cellid_mapping = True


# ── METHOD 3 only: Climate-adjusted coefficients ─────────────────────────────
# ⚠ Only used if ss_method = "using_copernicus_lulc_with_dynamic_coeff"; ignored otherwise.
#  Monthly weight formula: w_m = P_m^alpha × Q10^((T_m − T_ref) / 10)
#  Requires one entry per year in the simulation period.

ss_climate_data = {
    1993: {
        'precip_mm': [80, 70, 90, 100, 110, 120, 80, 60, 70, 90, 100, 85],  # Jan→Dec
        'temp_c':    [2,   3,  7,  12,  17,  22, 25, 24, 19, 13,   7,  3]
    },
    1994: {
        'precip_mm': [85, 75, 95, 105, 115, 125, 85, 65, 75, 95, 105, 90],
        'temp_c':    [1,   4,  8,  13,  18,  23, 26, 25, 20, 14,   8,  2]
    }
}
ss_climate_precip_scaling_power = 1.0    # Precipitation exponent (1.0 = linear scaling)
ss_climate_temp_q10 = 2.0               # Q10 factor: rate doubles per 10°C increase
ss_climate_temp_reference_c = 15.0       # Reference temperature [°C]


# ── METHOD 4: Machine Learning model ─────────────────────────────────────────
# ⚠ Only used if ss_method = "ml_model"; ignored otherwise.
#  Train a model from monitoring station data to predict loads.
#  Requires: pip install scikit-learn xgboost

ss_ml_training_data_csv = None         # Path to CSV with columns: date, discharge_m3s, precip_mm, temp_c, <species>
ss_ml_model_type = "xgboost"           # "xgboost" or "random_forest"
ss_ml_target_species = None            # e.g., ["NO3-N", "TP"]. None = auto-detect from CSV columns.
ss_ml_feature_columns = None           # e.g., ["discharge_m3s", "precip_mm"]. None = auto-detect.
ss_ml_n_estimators = 200               # Number of decision trees
ss_ml_max_depth = 6                    # Maximum tree depth (higher = more complex, risk of overfitting)


# ──────────────────────────────────────────────────────────────────────────────
#  SECTION 6: EXTERNAL WATER FLUXES
# ──────────────────────────────────────────────────────────────────────────────
#  Boundary conditions for water entering from outside the model domain
#  (e.g., upstream inflow with a fixed concentration).
#
#  "fixed_value" — Assign a constant concentration to an external flux
#  "none"        — No external water flux concentrations
#
#  ⚠  When using PHREEQC, set "none" unless the species name is a valid component.

ewf_method = "none"

# ── Fixed value settings ──
# ⚠ Only used if ewf_method = "fixed_value"; ignored otherwise.
ewf_method_fixedval_comment = "External model: summa"
ewf_method_fixedval_source = "Just for demonstration purposes"
ewf_method_fixedval_chem_name = "NO3-N"           # Species receiving the concentration
ewf_method_fixedval_value = 2.5                    # Concentration value
ewf_method_fixedval_units = "mg/l"                 # Concentration units
ewf_method_fixedval_external_inputflux_name = "SUMMA_RUNOFF"  # Name of the external flux


# ──────────────────────────────────────────────────────────────────────────────
#  SECTION 7: OUTPUT SETTINGS
# ──────────────────────────────────────────────────────────────────────────────
#  What to save, how often, and in what format.

# Output file format.
#   "HDF5" — one file per species × compartment (recommended, compact & fast)
#   "CSV"  — plain text (easier to read manually, but larger files)
output_format = "HDF5"

# Which chemical species to write to output files.
#   "all"  → auto-detect from the BGC module file:
#             NATIVE_BGC_FLEX: reads species keys from the JSON framework file
#             PHREEQC: uses phreeqc_mobile_species list
#   [list] → explicit list of species names (must match BGC module names)
chemical_species = "all"

# Concentration units in the output files.
units = "MG/L"

# Value written for dry cells (no water). Use a flag value to filter later.
no_water_conc_flag = -9999

# Also export sediment concentrations alongside dissolved species.
export_sediment = True

# How often to write output.
# Format: [value, unit] where unit is "second", "minute", "hour", or "day".
timestep = [1, "hour"]

# Which compartments and cells to export.
# Format: { "COMPARTMENT": { "ix_range": ["iy_range", "iz_range", "cell_range"] } }
# Use "all" to export every cell in that dimension.
compartments_and_cells = {
    "RIVER_NETWORK_REACHES": {
        "1": ["all", "all", "all"]
    }
}


# ──────────────────────────────────────────────────────────────────────────────
#  SECTION 8: DOCKER SETTINGS
# ──────────────────────────────────────────────────────────────────────────────
#  The generated HTML report includes ready-to-copy Docker commands.
#  Adjust the number of MPI processes below if needed.

# Number of MPI processes. Minimum 2 for mizuRoute.
mpi_np = 2


# ──────────────────────────────────────────────────────────────────────────────
#  SECTION 9: REPORT GENERATION (optional)
# ──────────────────────────────────────────────────────────────────────────────
#  Generates an HTML report after the simulation with:
#    • Model configuration summary
#    • Interactive basin map with river network
#    • Time series plots per species
#    • Spatial statistics
#    • Source/sink load summary
#    • Observation data comparison (if GRQA data available)

generate_report = True
open_report = True   # Automatically open the report in your browser when done.

# River network shapefile — used for the interactive map in the report.
# Set to None to skip the map, or provide a path to .shp or .gpkg.
# Basin polygons are automatically loaded from ss_method_copernicus_basin_info above.
river_network_shapefile = "/Users/diogocosta/Documents/openwq_code/diogo_test/mizuRoute-OpenWQ/route/build/openwq/openwq/bin/mizuroute_in/shapefiles/mizuSegId.shp"   # e.g., "/path/to/river_network.shp"

# GRQA observation data (Global River Water Quality Archive).
# Used to overlay real monitoring station locations on the map and
# generate a data availability report for your species.
#
# Options:
#   "auto" → auto-download from Zenodo (one-time ~1.2 GB download, cached locally).
#            Only CSVs matching your species are extracted from the archive.
#   "/path/to/grqa/" → use a pre-downloaded GRQA folder.
#            Download: https://zenodo.org/records/15335450
#   "skip"  → skip GRQA entirely (no station overlay, no data report)
grqa_local_data_path = "auto"

# Buffer distance [km] around the basin boundary (or river network if no basin
# shapefile is provided) for searching GRQA monitoring stations.
# Increase for remote catchments with sparse monitoring coverage.
grqa_buffer_km = 10


# ╔════════════════════════════════════════════════════════════════════════╗
# ║  END OF USER CONFIGURATION — do not edit below this line               ║
# ╚════════════════════════════════════════════════════════════════════════╝

import webbrowser
from Gen_Report import generate_report as _generate_report

# Derive output directory from executable path (files go where the executable lives)
dir2save_input_files = os.path.dirname(os.path.abspath(executable_path))
# Resolve chemical_species = "all" before passing to driver and report
if (isinstance(chemical_species, str) and chemical_species.lower() == "all") or \
   (isinstance(chemical_species, list) and len(chemical_species) == 1
    and isinstance(chemical_species[0], str) and chemical_species[0].lower() == "all"):
    chemical_species = gJSON_lib.extract_species_from_bgc(
        bgc_module_name=bgc_module_name,
        path2selected_NATIVE_BGC_FLEX_framework=path2selected_NATIVE_BGC_FLEX_framework,
        phreeqc_mobile_species=locals().get('phreeqc_mobile_species'),
    )

# 1) Generate configuration files
_excluded = {'sys', 'os', 'webbrowser', 'gJSON_lib', 'uniform_param',
             '_generate_report'}
_config = {k: v for k, v in locals().items()
           if not k.startswith('_') and k not in _excluded}
gJSON_lib.Gen_Input_Driver(**_config)

print("\n" + "=" * 60)
print("CONFIG FILES GENERATED SUCCESSFULLY")
print("=" * 60)
print(f"  Output directory: {dir2save_input_files}")
print(f"  Master JSON:      {dir2save_input_files}/openWQ_master.json")
print(f"  Input files:      {dir2save_input_files}/openwq_in/")

# 2) Generate report (optional)
_report_path = None
if generate_report:
    # Basin shapefile from Copernicus config (if available)
    _basin_shp = None
    try:
        _basin_shp = ss_method_copernicus_basin_info.get('path_to_shp')
    except (NameError, AttributeError):
        pass

    _report_path = _generate_report(
        dir2save_input_files=dir2save_input_files,
        project_name=project_name,
        authors=authors,
        date=date,
        comment=comment,
        hostmodel=hostmodel,
        bgc_module_name=bgc_module_name,
        td_module_name=td_module_name,
        le_module_name=le_module_name,
        ts_module_name=ts_module_name,
        si_module_name=si_module_name,
        ss_method=ss_method,
        solver=solver,
        chemical_species=chemical_species,
        units=units,
        compartments_and_cells=compartments_and_cells,
        timestep=timestep,
        river_network_shapefile=river_network_shapefile,
        basin_shapefile=_basin_shp,
        grqa_local_data_path=grqa_local_data_path,
        grqa_buffer_km=grqa_buffer_km,
        mpi_np=mpi_np,
        executable_path=executable_path,
        file_manager_path=file_manager_path,
    )

print("\n" + "=" * 60)
print("DONE")
print("=" * 60)

# 4) Open report in browser (optional)
if generate_report and open_report and _report_path and os.path.isfile(_report_path):
    print(f"  Opening report: {_report_path}")
    webbrowser.open(f"file://{os.path.abspath(_report_path)}")
